export const CLIENT_DETAILS_REQUEST = 'CLIENT_DETAILS_REQUEST'
export const CLIENT_DETAILS_SUCCESS = 'CLIENT_DETAILS_SUCCESS'
export const CLIENT_DETAILS_FAIL = 'CLIENT_DETAILS_FAIL'

export const CLIENT_CREATE_REQUEST = 'CLIENT_CREATE_REQUEST'
export const CLIENT_CREATE_SUCCESS = 'CLIENT_CREATE_SUCCESS'
export const CLIENT_CREATE_FAIL = 'CLIENT_CREATE_FAIL'
export const CLIENT_CREATE_RESET = 'CLIENT_CREATE_RESET'


export const MANUFACTURER_DETAILS_REQUEST = 'MANUFACTURER_DETAILS_REQUEST'
export const MANUFACTURER_DETAILS_SUCCESS = 'MANUFACTURER_DETAILS_SUCCESS'
export const MANUFACTURER_DETAILS_FAIL = 'MANUFACTURER_DETAILS_FAIL'


export const MANUFACTURER_CREATE_REQUEST = 'MANUFACTURER_CREATE_REQUEST'
export const MANUFACTURER_CREATE_SUCCESS = 'MANUFACTURER_CREATE_SUCCESS'
export const MANUFACTURER_CREATE_FAIL = 'MANUFACTURER_CREATE_FAIL'
export const MANUFACTURER_CREATE_RESET = 'MANUFACTURER_CREATE_RESET'

export const MANUFACTURER_DELETE_REQUEST = 'SUPPLIER_DELETE_REQUEST'
export const MANUFACTURER_DELETE_SUCCESS = 'SUPPLIER_DELETE_SUCCESS'
export const MANUFACTURER_DELETE_FAIL = 'SUPPLIER_DELETE_FAIL'


export const SUPPLIER_DETAILS_REQUEST = 'SUPPLIER_DETAILS_REQUEST'
export const SUPPLIER_DETAILS_SUCCESS = 'SUPPLIER_DETAILS_SUCCESS'
export const SUPPLIER_DETAILS_FAIL = 'SUPPLIER_DETAILS_FAIL'

export const SUPPLIER_CREATE_REQUEST = 'SUPPLIER_CREATE_REQUEST'
export const SUPPLIER_CREATE_SUCCESS = 'SUPPLIER_CREATE_SUCCESS'
export const SUPPLIER_CREATE_FAIL = 'SUPPLIER_CREATE_FAIL'
export const SUPPLIER_CREATE_RESET = 'SUPPLIER_CREATE_RESET'

export const SUPPLIER_DELETE_REQUEST = 'SUPPLIER_DELETE_REQUEST'
export const SUPPLIER_DELETE_SUCCESS = 'SUPPLIER_DELETE_SUCCESS'
export const SUPPLIER_DELETE_FAIL = 'SUPPLIER_DELETE_FAIL'
export const SUPPLIER_DELETE_RESET = 'SUPPLIER_DELETE_RESE'
