export const CLIENT_DETAILS_REQUEST = 'CLIENT_DETAILS_REQUEST'
export const CLIENT_DETAILS_SUCCESS = 'CLIENT_DETAILS_SUCCESS'
export const CLIENT_DETAILS_FAIL = 'CLIENT_DETAILS_FAIL'

export const CLIENT_CREATE_REQUEST = 'CLIENT_CREATE_REQUEST'
export const CLIENT_CREATE_SUCCESS = 'CLIENT_CREATE_SUCCESS'
export const CLIENT_CREATE_FAIL = 'CLIENT_CREATE_FAIL'
export const CLIENT_CREATE_RESET = 'CLIENT_CREATE_RESET'